accelerate launch --config_file ./config.yaml src/train_bash.py \
    --stage rm \
    --model_name_or_path meta-llama/Llama-2-13b-chat-hf \
    --do_train \
    --dataset dolly_train \
    --template llama2 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj,k_proj,o_proj \
    --resume_lora_training False \
    --output_dir "./results/balanced_entropy_rm_splits/train_dolly_lr4_13b" \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 10000 \
    --learning_rate 1e-4 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --fp16